### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by shilun** [jiayisheji/ng4-admin-pro#1]
ERROR in ng4-admin-pro/src/app/shared/breadcrumb/breadcrumb.component.ts (3,22): Cannot find module '../nav'.
ERROR inng4-admin-pro/src/app/shared/breadcrumb/breadcrumb.module.ts (4,22): Cannot find module '../nav'.

**Comment by jiayisheji** [comment]
@shilun [fixed](https://github.com/jiayisheji/ng4-admin-pro/commit/542d91364516d89a0a063bc780e33cd29cd3b45b)
